### ISSUE TITLE
[Approche] Ajouter la partie "Pour nous, faire évoluer l'industrie du logiciel..."

### ISSUE THREAD

**Issue by GuillaumeCz** [sogilis/sogilis.fr#28]
- [ ] Redimension de l'image 
- [ ] Ajout du texte
![image](https://user-images.githubusercontent.com/10077381/95566758-4f44b200-0a22-11eb-9d98-c054d9d43397.png)

**Comment by m-wy** [comment]
Image responsive pas besoin de la toucher si je comprends bien
